### ISSUE TITLE
[Bug] Wrong version number in composer.json for tag 1.1.2

### ISSUE THREAD

**Issue by Stevie-Ray** [ho-nl/magento2-nl_NL#11]
Please update the tagged commit to the updated composer.json to add the v1.1.2 to packagist/composer. Also the magento2-nl_NL/src/etc/module.xml is still on v1.1.1

**Comment by pascaladriaansen** [comment]
Seconding this. And if you're at it, could you guys please release version `1.1.3` including cceedba865d8048631f4374f83b083aabb39af32?

**Comment by paales** [comment]
Will create a new version :)

**Comment by JeroenVanLeusden** [comment]
New version has been released.
