### ISSUE TITLE
Translation "Middle Name/Initial"

### ISSUE THREAD

**Issue by Stevie-Ray** [ho-nl/magento2-nl_NL#17]
The translation for **Middle Name/Initial** is missing, is this something we can add to the _honl.csv_? As it is used in the core Magento_Customer module (Setup/InstallScheme.php)

**Comment by JeroenVanLeusden** [comment]
I've added the missing strings and opened a PR in the Magento repository (https://github.com/magento/magento2/pull/10604).

All the translations are taken from Crowdin so once merged they'll be included in this module. In the meantime you can create a module and add the missing translations.
