### ISSUE TITLE
Installatie instructies

### ISSUE THREAD

**Issue by OwenRay** [ho-nl/magento2-nl_NL#2]
Ik kwam er niet helemaal met de installatie instructies:
Uiteindelijk heb ik in m'n composer bestand een repository toegevoegd:
```
        "0": {
            "type": "vcs",
            "url": "https://github.com/ho-nl/magento2-nl_NL"
        }
```

en onder require:
`    "honl/magento2-nl-nl": "^0.2.0"`

Daarna pakte hij hem met `composer update`

**Comment by paales** [comment]
De vendor folder is gerenamed naar `honl/magento2-nl-nl` (heeft er mee te maken dat Magento geen `-`-tekens in de vendor naam accepteert. Om deze reden moest ik het pakket renamen.

Inmiddels is een nieuwe versie geüpload naar [Packagist](https://packagist.org/packages/honl/magento2-nl-nl) en de installatie instructies moeten weer werken.

**Comment by paales** [comment]
@OwenRay Het kan dus zijn dat je moet reinstallen:

```
composer remove ho-nl/magento2-nl-nl
composer install honl/magento2-nl-nl
```
