### ISSUE TITLE
Van Aan

### ISSUE THREAD

**Issue by maartenv1** [ho-nl/magento2-nl_NL#23]
From,Van,module,Magento_Backend
To,Aan,module,Magento_Backend

Moet zijn: 
From,Van,module,Magento_Backend
To,Tot,module,Magento_Backend

From,Van,module,Magento_Bundle
To,Aan,module,Magento_Bundle

Moet zijn
From,Van,module,Magento_Bundle
To,Tot,module,Magento_Bundle

**Comment by PascalBrouwers** [comment]
Please submit these changes in https://crowdin.com/project/magento-2/
