### ISSUE TITLE
Translation for Magento_CatalogRuleStaging

### ISSUE THREAD

**Issue by VadimDraganyuk** [ho-nl/magento2-nl_NL#26]
Have a problem with translation. Fore example code:
`jQuery.mage.__("1")` return `200`. 
Debug show that is this line changing translation
`200,200,module,Magento_CatalogRuleStaging`
If I change this line to  `200,1,module,Magento_CatalogRuleStaging` then translation good, but is no way to resolve problem offcourse, because 200 is no 1 ).
The same with `jQuery.mage.__("2")` return `100` 
`100,100,module,Magento_CatalogRuleStaging`
I hope that is magento bug but what is Magento_CatalogRuleStaging and why need add this translation?

**Comment by JeroenVanLeusden** [comment]
Hi @VadimDraganyuk,

The Magento_CatalogRuleStaging module is a part of the staging functionality in Magento EE. It enables you to add the catalog rule updates to existing store campaigns. In other words, you can add and/or remove catalog rules for some period of time. These updates are shown on the campaign dashboard.

I'm not sure why you're having this issue but if you're just using numbers you can try to omit the translation method.

**Comment by VadimDraganyuk** [comment]
Hi
I can not to omit because is not custom module has this translation. I dont know why developers translated numbers, but now I have to override file and with each new module version check if this file was changed. Maybe is fixed in 2.2.2 version, will see.

Thanks for ansver.
