### ISSUE TITLE
Language update + je / u

### ISSUE THREAD

**Issue by jeroencusters** [ho-nl/magento2-nl_NL#29]
I have two questions:
1) When will you update this extension? I found a typo in a translation, when I checked crowdin the typo was updated 5 months ago.

2) I see both 'je' and 'U' in the translation files. We would like to have one standard ('je'). Do I need to override these translations  

Thanks for your help!

**Comment by JeroenVanLeusden** [comment]
Hi @jeroencusters,

1. We've just pushed the latest changes to the develop branch. One translations is updated.
2. Overriding translations is possible by creation a new translation pack. Or you can update the translations in Crowdin so they end up in this module.
