### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by RobinBrons** [ho-nl/magento2-nl_NL#3]
Change `composer require honl/magento2-nl-nl` to `composer require honl/magento2-ho-nl`

**Comment by paales** [comment]
@RobinBrons This has already happened a few days ago: https://github.com/ho-nl/magento2-nl_NL/commit/a9318aab95d715050fdb5bc8504749701c7bf1da

**Comment by paales** [comment]
@RobinBrons There is a new version available on packagist, everything should be good to go. https://packagist.org/packages/honl/magento2-nl-nl
