### ISSUE TITLE
Not all words are translated.

### ISSUE THREAD

**Issue by lvgreay** [ho-nl/magento2-nl_NL#31]
Hi,
Many words are still in EN. see attachments please. 
Any idea how to fix it?
thank you
![nl2](https://user-images.githubusercontent.com/40840837/42295412-5b6d097a-7fea-11e8-87fb-497b7ad784e5.PNG)
![nl1](https://user-images.githubusercontent.com/40840837/42295413-5b881972-7fea-11e8-9a0b-400864314714.PNG)
![nl](https://user-images.githubusercontent.com/40840837/42295414-5ba08f34-7fea-11e8-9ceb-7a2eb8baf53c.PNG)

**Comment by JeroenVanLeusden** [comment]
Hi,

The develop branch is updated with the newest translations. Some strings you mentioned aren't translatable within Magento. This PR will solve that in a next version of Magento: https://github.com/magento/magento2/pull/16553

- `View and edit cart` is already translated if you check the file.
- `Go to checkout` and `search...` are not strings used in Magento.

You might want to check if your static content is deployed correctly. Strings added in your theme can be translated yourself.
