### ISSUE TITLE
Allow PHP 7.2

### ISSUE THREAD

**Issue by Swahjak** [ho-nl/magento2-nl_NL#34]
While testing with Magento 2.3 in combination with PHP 7.2 I ran into `honl/magento2-nl-nl 1.1.9 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.8) does not satisfy that requirement.` Magento 2.3 will be supporting PHP 7.2 https://github.com/magento/magento2/blob/2.3-develop/composer.json so I would like to ask if the dependency could be changed.

**Comment by JeroenVanLeusden** [comment]
Fixed in v1.1.10
