### ISSUE TITLE
after installing the Dutch language file, icons and menu not working

### ISSUE THREAD

**Issue by deloenzien** [ho-nl/magento2-nl_NL#38]
After installing the the Dutch language pack and logging in admin all icons are changed to E30b, e4ob,etc.. and CSS of menu's are not pulling(viewing).
Installed with wizard.
[https://shop.goodlook.be/mystuff/afterDutch installation.jpg](url)

**Comment by JeroenVanLeusden** [comment]
Don't think this is an issue with the module but with missing static content. You can run `bin/magento setup:static-content:deploy` to generate static content.
