### ISSUE TITLE
Translation seem off

### ISSUE THREAD

**Issue by Darkbelg** [ho-nl/magento2-nl_NL#41]
The following translation seems off when used in a certain context.
"Use as my default shipping address","Gebruik mijn standaard verzendadres",module,Magento_CustomerCustomAttributes

This should be "Gebruik als mijn standaard verzendadres" or "Gebruik als standaard verzendadres"

Here is a screenshot from what i mean. You can find this translation when editing a address in your account on the frontend.
![Screen Shot 2019-03-21 at 13 10 27](https://user-images.githubusercontent.com/5646516/54751292-c6b1b700-4bda-11e9-84b7-273a06d8c7cf.png)

**Comment by JeroenVanLeusden** [comment]
Hi @Darkbelg,

You can update translations [here](https://crowdin.com/translate/magento-2/all/enus-nl). After that we can import the updated translations.

**Comment by Darkbelg** [comment]
Done
