### ISSUE TITLE
Build script is not reachable

### ISSUE THREAD

**Issue by jghaanstra** [ho-nl/magento2-nl_NL#43]
curl: (7) Failed to connect to 107.170.242.99 port 80: Connection timed out

**Comment by jghaanstra** [comment]
Anyone?

**Comment by lvgreay** [comment]
Connecting to 107.170.242.99:80... failed: Connection timed out.
Any reason?

**Comment by lvgreay** [comment]
many words are still wrong, which need to be change. but the 107.170.242.99:80 is not reachable?
Any solution?

**Comment by jorgb90** [comment]
Is this going to be solved?

**Comment by JeroenVanLeusden** [comment]
Please check https://github.com/magento-l10n/language-nl_NL for up-to-date translations.
