### ISSUE TITLE
composer foutmelding ho-nl

### ISSUE THREAD

**Issue by SolsWebdesign** [ho-nl/magento2-nl_NL#5]
In de readme.md staat : Install: composer require honl/magento2-ho-nl
dan krijg ik de foutmelding "Your requirements could not be resolved to an installable set of packages". Ik heb van alles geprobeerd, pas na wat rondzoeken in de gesloten issues begreep ik dat ik moest doen : 
composer require honl/magento2-nl-nl
Is het een idee om readme.md aan te passen?

**Comment by paales** [comment]
@SolsWebdesign Fixed!
